[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Erik Lee <eriklee113@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.1"
aoc-runner-derive = "0.1.2"
counter = "0.4.3"
regex = "1"
lazy_static = "1.2"
